### ISSUE TITLE
Response does not throw an error when sending twice

### ISSUE THREAD

**Issue by siavol** [eugef/node-mocks-http#262]
Node.js does not allow to send response twice, so the following header
```js
function handler(req, res) {
  res.send('You can not send response twice!');
  res.send('This will throw an error');
}
```
will generate an error:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:603:11)
    ...
```

But `node-mock-http` (ver. 1.12.1) is not throwing any error and this unit test fails:
```js
test('handler throws when sending response twice', () => {
    const req = httpMocks.createRequest({
        method: 'GET',
        url: '/'
    });
    const res = httpMocks.createResponse();

    expect(() => handler(req, res)).toThrow();
})
```

**Comment by eugef** [comment]
HI @siavol, could you please check if version 1.11.0 has the same behaviour?

**Comment by siavol** [comment]
@eugef , I confirm that 1.11.0 has the same behaviour.

**Comment by siavol** [comment]
I took a look at the code and it is pretty straightforward to not allow setting headers after they are sent to the client. But [mockResponse.send](https://github.com/howardabrams/node-mocks-http/blob/master/lib/mockResponse.js#L154) does not set any headers, so that change will be not enough. Also comment explicitly says that `send` can be called multiple times. I wonder what is the reason of this decision?

**Comment by eugef** [comment]
That code was written almost 8 years ago, so not sure if we can figure out the reason.

The proper behaviour for the mock would be to throw the same type of error.
If you can create a PR with the fix - your help will be much appreciated.

**Comment by siavol** [comment]
Thank you! I am ready to take care of this issue. Going to provide PR in a few days.

**Comment by siavol** [comment]
I've prepared a pull request: https://github.com/howardabrams/node-mocks-http/pull/263

**Comment by HartS** [comment]
@eugef do you know why this issue (and corresponding PR) were closed? I realize the PR itself didn't get feedback addressed, but this is still an issue, right?

**Comment by eugef** [comment]
Github bot regularly closes stale issues and PRs

The issue still exists, you can help fixing it by improving this PR https://github.com/eugef/node-mocks-http/pull/263

**Comment by HartS** [comment]
Thanks @eugef . I'm kind of just getting familiar of the ergonomics of using this library.

I assume it's also be possible to spy on the res.send function to ensure it's not called more than once, and now I'm wondering if it's better to have the flexibility to allow some tests to send more than once (for example, I have req and res regenerated in a beforeEach, but if I wanted to run through the same middleware I'm testing twice in the same test, then it might be useful that res.send can be called twice)

Feel free to close, and I may re-open with a PR that makes sense to me once I have a better idea of the ways this can be used.
