### ISSUE TITLE
Provide decorator for stream consumer through pipe

### ISSUE THREAD

**Issue by tzkmx** [eugef/node-mocks-http#276]
> However I strongly feel that original API should be built on top of stream not the event

_Originally posted by @amitguptagwl in https://github.com/eugef/node-mocks-http/issues/166#issuecomment-377493744_

Extending the Stream prototype [has been tried](https://github.com/eugef/node-mocks-http/pull/169) but created [issues](https://github.com/eugef/node-mocks-http/issues/174) that were reverted at the immediate posterior release.

There are several issues raised around support for Streams, and probably without breaking the current API, we can provide a decorator for `request.pipe()` that would make easier to integrate with handlers that expect a ReadableStream rather than json or urlencoded body.

**Comment by eugef** [comment]
I think this is related to #277
