### ISSUE TITLE
Let mock request extend stream.Readable or even http.IncomingMessage

### ISSUE THREAD

**Issue by hbgl** [eugef/node-mocks-http#279]
In an effort to make the mock request behave more like a real [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage), it would make sense to extend from [stream.Readable](https://nodejs.org/api/stream.html#class-streamreadable) which is the base class of [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage)). There has been PR https://github.com/eugef/node-mocks-http/pull/169 that did attempt to extend from [stream.Readable](https://nodejs.org/api/stream.html#class-streamreadable) but it did not properly implement the [Readable protocol](https://nodejs.org/api/stream.html#api-for-stream-implementers) which led to issue https://github.com/eugef/node-mocks-http/issues/174.

I also think there is the possibility of inheriting directly from [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage). This would would require the mock to rely on some of Node's implementation details which have been [reasonably stable](https://github.com/nodejs/node/commits/main/lib/_http_incoming.js). The big advantage would be that the mock could reuse a large portion of the logic, including the complicated [header handling](https://github.com/nodejs/node/blob/32245275b50a455713ff753de6b1be494e077464/lib/_http_incoming.js#L279).

@eugef
Which of the two options, if any, would you prefer? I would be very happy to work on a PR for this feature.

**Comment by eugef** [comment]
Which approach is easier to implement and might give less backwards incompatible changes?

**Comment by hbgl** [comment]
The Readable approach is definitely easier to implement and more backwards compatible than IncomingMessage. One might get away with extending Readable without bumping the major version. Extending IncomingMessage, on the other hand, would be more akin to a rewrite of the mock request.

**Comment by eugef** [comment]
Ok, then I'd prefer extending from [stream.Readable](https://nodejs.org/api/stream.html#class-streamreadable)
