### ISSUE TITLE
@types/express should be a non-dev dependency

### ISSUE THREAD

**Issue by jfirebaugh** [eugef/node-mocks-http#289]
`@types/express` is a devDependency: https://github.com/eugef/node-mocks-http/blob/236d9020b254f67a30e3e2ae5d643678f0a546a6/package.json#L62

However, its types are imported in `lib/http-mock.d.ts`, which forms part of the public API: https://github.com/eugef/node-mocks-http/blob/236d9020b254f67a30e3e2ae5d643678f0a546a6/lib/http-mock.d.ts#L1

Therefore the dependency on `@types/express` should be a normal dependency, not a devDependency.

**Comment by eugef** [comment]
Hi @jfirebaugh thanks for reporting an issue.

The fix was released in version `1.14.1`
