### ISSUE TITLE
'links' function not defined

### ISSUE THREAD

**Issue by mocotrah** [eugef/node-mocks-http#294]
Hi, I have a test using the Express Response.links function.
When I use node-mocks-http it gives an error stating that the function 'links' is not defined.
Is it possible you implement this? Thanks.

**Comment by eugef** [comment]
Hi @mocotrah, indeed mock for [links()](https://expressjs.com/en/4x/api.html#res.links) function is not implemented .

This project depends heavily on bug fixes and feature improvements from various collaborators. 
So, if you need this feature urgently, the most straightforward option is to create a pull request with a fix.
