### ISSUE TITLE
Question: How to mock an request error?

### ISSUE THREAD

**Issue by mlshohet** [eugef/node-mocks-http#296]
Hello, I was wondering if you knew a technique to mock an error on the request? I need to test if the response is an error.

Love the library, such a great job!

Thanks for any help!

**Comment by eugef** [comment]
Hi @mlshohet can you give an example what kind of error in request do you want to mock?

**Comment by mlshohet** [comment]
Hi @eugef, thank you so much for the reply! I'm sorry about the bother. I was looking how to test for network errors. I figured out if there's no body on response I can just throw an exception or send an error code. Then I could catch the error, or check for this error code and handle it. This works for the tests. Best!
