### ISSUE TITLE
The `sendFile` property is missing

### ISSUE THREAD

**Issue by ChrisMBarr** [eugef/node-mocks-http#301]
As mentioned before in issues #88 and #245 (which were both closed without resolving!) the `sendFile` method is missing from this implementation.  The TypeScript typedefs say it is there, but it is not at runtime.

To reproduce in a Jest test:
```ts
import * as httpMock from 'node-mocks-http';

const res = httpMock.createResponse();
jest.spyOn(res, 'sendFile');
//               ^^^^^^^^  Property `sendFile` does not exist in the provided object
```

----

My temporary workaround to allow me to mock this method is to do this:
```ts
import * as httpMock from 'node-mocks-http';

export function createMockResponse() {
  const res = httpMock.createResponse();
  res.sendFile = () => {};
  return res;
}
```
```ts
import { createMockResponse } from '../test-helpers';

const res = createMockResponse();
jest.spyOn(res, 'sendFile');
```

**Comment by eugef** [comment]
Hi @ChrisMBarr thanks for reporting an issue.

This project heavily relies on contributors, so would be great if you can also submit a fix.
