### ISSUE TITLE
Express 5 types released - deduplication problem

### ISSUE THREAD

**Issue by RobinTail** [eugef/node-mocks-http#307]
Good news: `@types/express@5.0.0` released.
However, this line leads to multiple versions installed on consumer side:

https://github.com/eugef/node-mocks-http/blob/40e0e7595703da44cc752767e18e3b51f41efcfe/package.json#L49

Would it be possible somehow to address this?

An approach could be moving `@types/express` to `peerDependencies` (and probably `devDependencies` for building purposes). So that consumer would decide which version of `@types/express` to use accordingly.

I also noticed, that those types are only used to define defaults for `RequestType`. Another approach could be removing defaults.

Third option could be defining dependency with `>=`or as `*`, which however would lead to v5 by default, that can consequently by corrected by `resolution`/`overrides` entry on consumer side.

What do you think, @eugef ?

**Comment by eugef** [comment]
Hi @RobinTail, if it easy to remove `@types/express` dep - let's do this, otherwise I'd go for the `peerDependencies` approach.

**Comment by RobinTail** [comment]
Ok. Then I propose making a conceptual change to the following idea:

> Unless specified explicitly, they will be return an Express-based request/response

(it's from Readme)

https://github.com/eugef/node-mocks-http/blob/40e0e7595703da44cc752767e18e3b51f41efcfe/README.md?plain=1#L78 

so that it would be different:

- You SHOULD specify the type of request/response object of your framework;
- Otherwise the following types are used by default: `http.IncomingMessage` and `http.OutgoingMessage`

(wording is a subject to collaborate on).

That would allow to detach from `@types/express` and delegate to consumer supplying an explicit type according to the installed version of `express` and `@types/express`.

I will try my best on making a corresponding PR, @eugef

**Comment by eugef** [comment]
This sounds to me like a backwards incompatible change - let's not go this way.

I am fine with moving `@types/express` to the `peerDependencies`

**Comment by RobinTail** [comment]
> I am fine with moving @types/express to the peerDependencies

That would also be a breaking change, @eugef

**Comment by RobinTail** [comment]
> I am fine with moving @types/express to the peerDependencies

Yeah, I can make an alternative implementation using this approach, so you could compare them...
Stand by :)

**Comment by eugef** [comment]
> > I am fine with moving @types/express to the peerDependencies
> 
> That would also be a breaking change, @eugef

It would be much less "breaking" change.

For many projects `node-mocks-http` is not the only package that depends on `@types/express` so they won't notice any difference, otherwise npm and yarn will show a warning.

BTW, for consistency let's also move `@types/node` to `peerDependencies` as well

**Comment by RobinTail** [comment]
Check this out, @eugef : 
https://github.com/eugef/node-mocks-http/pull/309

It's actually really prettier and smaller change.
For those using pure JavaScript nothing will change at all.
TypeScript users would have to install their own `@types/express` and `@types/node`.

**Comment by eugef** [comment]
@RobinTail, thanks for your contribution,
This fix is published in version 1.16.1
